[tool.pinto]
steps = [
    "infer:launch-infer"
]

[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
accounting_group_user = "${LIGO_USERNAME}"
accounting_group = "${LIGO_GROUP}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']

repository_directory = "${BASE_DIR}/model_repo/"
Tb = 5184000  # 60 days of background
inference_batch_size = 128
inference_psd_length = 64

fduration = 1
verbose = true


[tool.typeo.scripts.launch-infer]

# paths
base_dir = "${base.basedir}"
model_repo_dir = "${base.repository_directory}"
data_dir = "${base.datadir}/test/background"
injection_set_file = "${base.datadir}/test/waveforms.h5"
log_dir = "${base.logdir}"

inference_sampling_rates = [1, 2, 4, 8, 16, 64]

# condor args
accounting_group_user = "${base.accounting_group_user}"
accounting_group = "${base.accounting_group}"

# triton args
model_name = "aframe-stream"
model_version = -1
image = "hermes/tritonserver:22.12"
sequence_id = 1001

# timeslide args
Tb = "${base.Tb}"
shifts = [0, 1]
throughput = 6400

# data args
sample_rate = "${base.sample_rate}"
inference_sampling_rate = "${base.inference_sampling_rate}"
batch_size = "${base.inference_batch_size}"
ifos = "${base.ifos}"
chunk_size = 4096

# analysis args
integration_window_length = 1
cluster_window_length = 8
fduration = "${base.fduration}"
psd_length = "${base.inference_psd_length}"

# misc
verbose = "${base.verbose}"
