[tool.pinto]
steps = [
    "generate_waveforms:generate-waveforms",
    "generate_glitches:generate-glitches",
]

[tool.typeo.base]
outdir = "${OUT_DIR}"
sample_rate = 2048
ifos = ['H1', 'L1']

[tool.typeo.scripts.generate-glitches]
snr_thresh = 8
window = 2
start = 1263588390
stop = 1263592390
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
f_min = 32
q_min = 3.3166
q_max = 108
cluster_dt = 0.5
chunk_duration = 124
segment_duration = 64 
overlap = 4 
mismatch_max = 0.2
state_flag = "DCS-ANALYSIS_READY_C01:1"

ifos = "${base.ifos}"
outdir = "${base.outdir}"
sample_rate = "${base.sample_rate}"

[tool.typeo.scripts.generate-waveforms]
outdir = "${base.outdir}"
n_samples = 10000
prior_file = "./generate_waveforms/priors/nonspin_BBH.prior"
sample_rate = "${base.sample_rate}" 
waveform_duration = 8
