[tool.poetry]
name = "train"
version = "0.1.0"
description = "Train BBHnet"
authors = ["ethan.marx <ethan.marx@ligo.org>"]
license = "MIT"
#readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
"bbhnet.data" = {path = "../../../libs/data", develop  = true}
"bbhnet.logging" = {path = "../../../libs/logging", develop = true}
"bbhnet.trainer" = {path = "../../../libs/trainer", develop = true}

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu116"
secondary = true
default = false

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"

[tool.poetry.scripts]
train = "train.train:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
