[tool.pinto]
steps = [
    #"generate_background:generate-background",
    #"generate_waveforms:generate-waveforms",
    #"generate_glitches:generate-glitches",
    #"train:train:resnet",
    #"export:export-model:resnet",
    #"timeslide_injections:timeslide_injections",
    "infer:infer",
    "analyze:analyze"
]

[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']
start = 1262607622
stop = 1262620622
test_stop = 1262751694
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
state_flag = "DCS-ANALYSIS_READY_C01:1"
resnet = {layers = [3, 3, 3]}
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = false
kernel_length = 2
inference_sampling_rate = 16
fmin = 32
prior_file = "priors/nonspin_BBH.prior"
fduration = 1

[tool.typeo.scripts.generate-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
start = "${base.start}" 
stop = "${base.stop}" 
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_length = 8000
force_generation = "${base.force_generation}"

[tool.typeo.scripts.generate-glitches]
snr_thresh = 5
window = 2
start = "${base.start}"
stop = "${base.stop}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
f_min = "${base.fmin}"
q_min = 3.3166
q_max = 108
cluster_dt = 0.5
chunk_duration = 124
segment_duration = 64 
overlap = 4 
mismatch_max = 0.2
force_generation = "${base.force_generation}"
ifos = "${base.ifos}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
sample_rate = "${base.sample_rate}"

[tool.typeo.scripts.generate-waveforms]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
n_samples = 10000
prior_file = "${base.prior_file}"
sample_rate = "${base.sample_rate}" 
waveform_duration = 8
force_generation = "${base.force_generation}"

[tool.typeo.scripts.train]
hanford_background = "${base.datadir}/H1_background.h5"
livingston_background = "${base.datadir}/L1_background.h5"
glitch_dataset = "${base.datadir}/glitches.h5"
signal_dataset = "${base.datadir}/signals.h5"
valid_frac = 0.025
valid_stride = 0.0625

logdir = "${base.logdir}"
outdir = "${base.basedir}/training"

fduration = "${base.fduration}"
trigger_distance_size = -0.5
sample_rate = "${base.sample_rate}"
waveform_frac = 0.5
glitch_frac = 0.25
min_snr = 4
max_snr = 10000
highpass = "${base.fmin}"
kernel_length = "${base.kernel_length}" 
batch_size = 64
batches_per_epoch = 50
max_epochs = 200
lr = 1e-5
weight_decay = 1e-5
patience = 10
factor = 0.2
early_stop = 100
device = "cuda"
profile = false
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.export-model]
repository_directory = "${base.repository_directory}" 
outdir = "${base.logdir}"
num_ifos = 2 
kernel_length = "${base.kernel_length}" 
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
weights = "${base.basedir}/training/weights.pt"
streams_per_gpu = 10
verbose = true
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.timeslide_injections]
start = "${base.stop}" 
stop = "${base.test_stop}"
datadir = "${base.basedir}/timeslide_injections/"
logdir = "${base.logdir}"
prior_file = "${base.prior_file}"
spacing = 60
buffer = 10
n_slides = 10
jitter = 1
min_segment_length = 1024
shifts = [0, 1]
ifos = "${base.ifos}"
file_length = 4096
fmin = "${base.fmin}" 
sample_rate = "${base.sample_rate}"
channel = "${base.channel}"
frame_type = "${base.frame_type}" 
state_flag = "${base.state_flag}"
verbose = true

[tool.typeo.scripts.infer]
model_repo_dir = "${base.repository_directory}"
model_name = "bbhnet-stream"
data_dir = "${base.basedir}/timeslide_injections/" 
write_dir = "${base.basedir}/timeslide_injections/"
fields = ["injection", "background"]
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
model_version = -1
base_sequence_id = 1001
log_file = "${base.logdir}/infer.log"
num_workers = 1
fduration = "${base.fduration}"
verbose = true

[tool.typeo.scripts.analyze]
data_dir = "${base.basedir}/timeslide_injections/"
write_dir = "${base.basedir}/timeslide_injections/"
results_dir = "${base.basedir}/results/" 
window_length = 1.0
kernel_length = 1.0 
norm_seconds = [0, 10, 100, 1000]
t_clust = 5
max_tb = 20000
force = false
log_file = "${base.basedir}/log/analyze.log"
verbose = false
