[tool.pinto]
steps = [
    "generate_background:generate-background",
    "generate_waveforms:generate-waveforms",
    "generate_glitches:generate-glitches",
    "train:train:resnet",
    "export:export-model:resnet",
    "timeslide_injections:timeslide_injections",
    "infer:infer",
    "analyze:analyze"
]

[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
ifos = ['H1', 'L1']
start = 1262607622
stop = 1262620622
test_stop = 1262751694  
channel = "DCS-CALIB_STRAIN_CLEAN_C01"
frame_type = "HOFT_C01"
state_flag = "DCS-ANALYSIS_READY_C01:1"
resnet = {layers = [3, 3, 3]}
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = false
kernel_length = 2
inference_sampling_rate = 16
inference_batch_size = 128
minimum_frequency = 20
reference_frequency = 50
highpass = 32
prior = "bbhnet.injection.priors.nonspin_bbh"
fduration = 1
valid_frac = 0.25

[tool.typeo.scripts.generate-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
start = "${base.start}" 
stop = "${base.stop}" 
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_length = 8000
force_generation = "${base.force_generation}"

[tool.typeo.scripts.generate-glitches]
snr_thresh = 5
window = 2
start = "${base.start}"
stop = "${base.stop}"
test_stop = "${base.test_stop}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
f_min = "${base.highpass}"
q_min = 3.3166
q_max = 108
cluster_dt = 0.5
chunk_duration = 124
segment_duration = 64 
overlap = 4 
mismatch_max = 0.2
force_generation = "${base.force_generation}"
ifos = "${base.ifos}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
sample_rate = "${base.sample_rate}"

[tool.typeo.scripts.generate-waveforms]
minimum_frequency = "${base.minimum_frequency}" 
reference_frequency = "${base.reference_frequency}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
n_samples = 10000
prior = "${base.prior}"
sample_rate = "${base.sample_rate}" 
waveform_duration = 8
force_generation = "${base.force_generation}"

[tool.typeo.scripts.train]
# input and output paths
hanford_background = "${base.datadir}/H1_background.h5"
livingston_background = "${base.datadir}/L1_background.h5"
glitch_dataset = "${base.datadir}/glitches.h5"

waveform_dataset = "${base.datadir}/signals.h5"
logdir = "${base.logdir}"
outdir = "${base.basedir}/training"

# data generation and processing parameters
sample_rate = "${base.sample_rate}"
kernel_length = "${base.kernel_length}"
fduration = "${base.fduration}"

highpass = "${base.minimum_frequency}"
trigger_distance = -0.5
waveform_prob = 0.5
glitch_prob = 0.25
mean_snr = 10
std_snr = 4
min_snr = 2

# optimization parameters
batch_size = 512
batches_per_epoch = 200
max_epochs = 200
lr = 4e-3
min_lr = 1e-5
decay_steps = 10000
weight_decay = 1e-5
early_stop = 20
valid_frac = "${base.valid_frac}"
valid_stride = 0.0625

# misc params
device = "cuda"
profile = false
use_amp = false

# arch parameters
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.export-model]
# paths
repository_directory = "${base.repository_directory}" 
outdir = "${base.logdir}"
weights = "${base.basedir}/training/weights.pt"

# input-output mapping info
num_ifos = 2 
kernel_length = "${base.kernel_length}" 
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
batch_size = "${base.inference_batch_size}"

# repo/triton parameters
instances = 2
streams_per_gpu = 4
platform = "tensorrt_plan"
verbose = false
clean = true

# arch parameters
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.timeslide_injections]
# paths and what not
datadir = "${base.datadir}/timeslide_injections/"
logdir = "${base.logdir}"

# background parameters
start = "${base.stop}"
stop = "${base.test_stop}"
sample_rate = "${base.sample_rate}"
ifos = "${base.ifos}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
file_length = 4096
min_segment_length = 1024

# timeslide parameters
shifts = [0, 1]
n_slides = 10

# injection parameters
prior = "${base.prior}"
minimum_frequency = "${base.minimum_frequency}"
reference_frequency = "${base.reference_frequency}"
highpass = "${base.highpass}"
spacing = 60
buffer = 10
jitter = 2

# misc parameters
verbose = true

[tool.typeo.scripts.infer]
model_repo_dir = "${base.repository_directory}"
model_name = "bbhnet-stream"
data_dir = "${base.datadir}/timeslide_injections/" 
write_dir = "${base.basedir}/timeslide_injections/"
fields = ["injection", "background"]
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
batch_size = "${base.inference_batch_size}"
model_version = -1
base_sequence_id = 1001
log_file = "${base.logdir}/infer.log"
throughput_per_gpu = 1600
streams_per_gpu = 4
num_workers = 4
fduration = "${base.fduration}"
verbose = false

[tool.typeo.scripts.analyze]
data_dir = "${base.basedir}/timeslide_injections/"
write_dir = "${base.basedir}/timeslide_injections/"
results_dir = "${base.basedir}/results/" 
window_length = 1.0
norm_seconds = [0, 10, 100, 1000]
t_clust = 5
max_tb = 604800
force = false
log_file = "${base.logdir}/analyze.log"
verbose = false

[tool.typeo.scripts.vizapp]
timeslides_results_dir = "${base.basedir}/timeslide_injections/"
timeslides_strain_dir = "${base.datadir}/timeslide_injections"
ifos = "${base.ifos}"
start = "${base.stop}"
stop = "${base.test_stop}"
veto_definer_file = "./vetoes/H1L1-HOFT_C01_O3_CBC.xml"
gate_paths = {"H1" = "./vetoes/H1-O3_GATES_1238166018-31197600.txt" , "L1" = "./vetoes/L1-O3_GATES_1238166018-31197600.txt"}
train_data_dir = "${base.datadir}"
sample_rate = "${base.sample_rate}"
fduration = "${base.fduration}"
valid_frac = "${base.valid_frac}"
logdir = "${base.basedir}"
verbose = true
