name: aframe-datagen
channels:
  - conda-forge
dependencies:
  - python=3.9
  - libgcc
  # frame file I/O dependencies
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  # omicron dependencies
  - python-ligo-lw
  - omicron>=4.0.0
  - uproot
