# UPDATE THIS FILE TO HAVE BETTER FILTERING,
# PARALLELIZATION, AND TO NOT RUN IF A PR IS
# MARKED AS DRAFT OR HAS [skip-ci] IN ITS
# COMMIT MESSAGE

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter 
      with:
        filters: .github/filters.yaml
  
  tests:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: true # is this desired behavior here?
      matrix:
        library: ${{ fromJSON(needs.changes.outputs.libraries) }}
        args: [""]
        include:
          - library: '/libs/data'
            args: '-m "not gpu"'
         
         
           
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # install gcc for bilby build
      -
        name: install gcc
        run: apt update && apt install -y build-essential

      # run tests
      -
        name: run tests 
        env:
          test_dir: /github/workspace/${{ matrix.library }}
        run: |
          pinto -p $test_dir run pytest $test_dir/tests ${{matrix.args}}

     
