name: ci-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-tests:
    # set up Pinto container permissions
    if: github.repository_owner == 'ML4GW'
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # create filters for each lib so that we
      # only run the tests we absolutely need to
      -
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            io:
              - 'libs/io/**'
            analysis:
              - 'libs/analysis/**'
            injection:
              - 'libs/injection/**'
            data:
              - 'libs/data/**'
            generate_waveforms:
              - 'projects/generate_waveforms/**'

      # install gcc for bilby build
      -
        name: install gcc
        run: apt update && apt install -y build-essential

      # test injection library up front since multiple
      # libraries depend on it
      -
        name: run injection tests
        if: steps.filter.outputs.injection == 'true'
        env:
          test_dir: /github/workspace/libs/injection
        run: pinto run $test_dir pytest -x $test_dir/tests

      # run dataloader tests if dataloader library code changed
      # _or_ if injection code (on which it depends) changed
      -
        name: run dataloader tests
        if: |
          (steps.filter.outputs.injection == 'true')
          && (steps.filter.outputs.data == 'true')
        env:
          test_dir: /github/workspace/libs/data
        run: pinto run $test_dir pytest $test_dir/tests -m "not gpu"

      # test projects, and filter by both changes to
      # project code and their dependent libraries
      -
        name: run waveform tests
        if: |
          (steps.filter.outputs.injection == 'true')
          && (steps.filter.outputs.generate_waveforms == 'true')
        env:
          test_dir: /github/workspace/projects/generate_waveforms
        run: pinto run $test_dir pytest $test_dir/tests
