name: ci-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - uses: actions/checkout@v2
      -
        name: run dataloader tests
        env:
          test_dir: /github/workspace/libs/data
        run: pinto run $test_dir pytest $test_dir/tests -m "not gpu"
