name: Build and publish Docker image

on:
  pull_request:
  push:
    branch: main

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Log in to container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      -
        name: Rebuild and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true # ${{ github.repository_owner == 'ML4GW' && github.event_type == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
